<?php

namespace Uvweb\UvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
	public function averageRate(Uv $uv) {

		$qb = $this->createQueryBuilder('c');

		$qb->select('AVG(c.globalRate) as globalRate')
		   ->where('c.moderated = :moderated')->setParameter('moderated', true)
		   ->andWhere('c.uv = :uv')->setParameter('uv', $uv);

		return $qb->getQuery()->getSingleScalarResult();

	}

	public function userAlreadyCommentedUv(User $user, Uv $uv)
	{
		$qb = $this->createQueryBuilder('c');
		
		$qb->where('c.author = :author')->setParameter('author', $user->getId())
		   ->andWhere('c.uv = :uv')->setParameter('uv', $uv->getId());

		$comment = $qb->getQuery()->getOneOrNullResult();

		return $comment !== null;
	}

	private function prepareUvListQuery()
	{
		$qb = $this->createQueryBuilder('c');

		$qb->select('AVG(c.globalRate) AS globalRate')
            ->addSelect('COUNT(c.globalRate) AS commentCount')
            ->addSelect('u.name as name')
            ->join('c.uv', 'u')
		    ->where('c.moderated = :moderated')->setParameter('moderated', true)
		    ->andWhere('u.archived = :archived')->setParameter('archived', 0)
		    ->groupBy('name');

		return $qb;
	}

	public function uvsOrderedByRate($limit = 0, $best = true, $minCountComments = 0, $category = '')
	{
		$qb = $this->prepareUvListQuery();

		if(!empty($category))
		{
			if($category !== 'tsh')
			{	
				$qb->join('u.categories', 'cat')
				   ->andWhere('cat.category = :categorie')->setParameter('categorie', $category);
			}
			else
			{
				//TSH
				$qb->join('u.categories', 'cat')
				   ->andWhere('cat.category in (:tsh)')->setParameter('tsh', array('EC', 'ME', 'CT'));
			}
		}

		if($minCountComments > 0)
		    $qb->having('commentCount > :minCount')->setParameter('minCount', $minCountComments);

		if($best)
            $qb->orderBy('globalRate', 'DESC');
        else
            $qb->orderBy('globalRate', 'ASC');

        $qb->addOrderBy('name');

        if($limit > 0)
        	$qb->setMaxResults($limit);

		return $qb->getQuery()->getResult();
	}

	public function uvsOrderedByName($limit = 0, $category = '')
	{
		$qb = $this->prepareUvListQuery();

		if(!empty($category))
		{
			if($category !== 'tsh')
			{
				$qb->join('u.categories', 'cat')
				   ->andWhere('cat.category = :categorie')->setParameter('categorie', $category);
			}
			else
			{
				//TSH
				$qb->join('u.categories', 'cat')
				   ->andWhere('cat.category in (:tsh)')->setParameter('tsh', array('EC', 'ME', 'CT'));
			}
		}

        $qb->addOrderBy('name');

        if($limit > 0)
        	$qb->setMaxResults($limit);

		return $qb->getQuery()->getResult();
	}
}
