<?php

namespace Uvweb\UvBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findLastNews()
    {
        $queryBuilder = $this->createQueryBuilder('n');
        $queryBuilder->where('n.date >= :date')->setParameter('date', new \Datetime(date('Y').'-01-01')); //We don't have to retrieve the very old news...
        $queryBuilder->setMaxResults(20);
        $queryBuilder->orderBy('n.id', 'desc'); //Order by id: with autoincrement last news is the highest id number
        
        return $queryBuilder->getQuery()->getResult();
    }
}
