<?php

namespace Uvweb\UvBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class UvController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Uvweb\UvBundle\Controller\UvController();
        return $instance;
    }
}
